batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
  - mloubout/azure_elastic:v1.0
  volumes:
    shared_data_volumes:
      azureblob_vol:
        volume_driver: azureblob
        storage_account_settings: mystorageaccount
        azure_blob_container_name: <name of the blob container>
        container_path: $AZ_BATCH_NODE_SHARED_DIR/path/to/container/in/job
        bind_options: rw