job_specifications:
- id: test-tti-multinode
  auto_complete: false
  shared_data_volumes:
    - azureblob_vol
  infiniband: true
  tasks:
  - docker_image: slimcontainers.azurecr.io/devito_tti_mpi:v0.2
    additional_docker_run_options:
      - --privileged
    environment_variables:
      BLOB_CONTAINER: 'seismic'
      DEVITO_ARCH: intel
      OMP_NUM_THREADS: 8
      OMP_PROC_BIND: 'close'
      DEVITO_OPENMP: 1
      OMP_PLACES: 'cores'
      DEVITO_LOGGING: 'DEBUG'
      DEVITO_MPI: 1
      SPACE_ORDER: 12
      RESTRICT_MODEL: 'TRUE'
      BATCHSIZE: 2
      ITERATION: 1
      MAXITER: 1
      PARTIAL_GRAD_PATH: 'partial_gradients/'
      FULL_GRAD_PATH: 'full_gradients/'
      GRAD_NAME: 'bp_tti_grad_'
    task_factory:
      parametric_sweep:
        product:
        - start: 200
          step: 1
          stop: 202
    multi_instance:
      num_instances: 4
      pre_execution_command: source /opt/intel2019/bin/compilervars.sh intel64
      mpi:
        runtime: intelmpi
        processes_per_node: 1
    command: >
      python3 $AZ_BATCH_NODE_SHARED_DIR/seismic/scripts/app.py
      {}
