pool_specification:
  id: tti-multinode-pool
  vm_configuration:
    platform_image:
      offer: UbuntuServer
      publisher: Canonical
      sku: '16.04-LTS'
      native: true
  vm_count:
    dedicated: 2
    low_priority: 0
  vm_size: Standard_H16r
  inter_node_communication_enabled: true
  ssh:
    username: shipyard
    allow_docker_access: true
