batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
  - mloubout/azure_elastic:v2.0
  volumes:
    shared_data_volumes:
      azureblob_vol:
        volume_driver: azureblob
        storage_account_settings: mystorageaccount
        azure_blob_container_name: container name
        container_path: $AZ_BATCH_NODE_SHARED_DIR/path
        bind_options: rw