batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
    -  slimcontainers.azurecr.io/azure_devito_mpich:v0.14
  volumes:
    shared_data_volumes:
      azureblob_vol:
        volume_driver: azureblob
        storage_account_settings: mystorageaccount
        azure_blob_container_name: seismic
        container_path: $AZ_BATCH_NODE_SHARED_DIR/seismic
        bind_options: rw
