job_specifications:
- id: gtjob33
  auto_complete: true
  shared_data_volumes:
  - azureblob_vol
  tasks:
  - docker_image: slimcontainers.azurecr.io/azure_devito_mpich:v0.14
    environment_variables:
      OMP_NUM_THREADS: 16
      MODEL_PATH: seismic/models/
      DATA_PATH: seismic/data/
      GRADIENT_PATH: seismic/partial_gradients/
    # additional_docker_run_options:
    # - --privileged
    multi_instance:
      num_instances: pool_current_dedicated
      mpi:
        runtime: mpich
        processes_per_node: 1
    task_factory:
      random:
        generate: 1
        integer:
          start: 1
          step: 1
          stop: 1348
    command: ls -l $AZ_BATCH_NODE_SHARED_DIR/seismic
