job_specifications:
- id: gtjob1
  auto_complete: true
  environment_variables:
    OMP_NUM_THREADS: 16
  tasks:
  - docker_image: slimcontainers.azurecr.io/azure_devito_mpich:v0.9
    additional_docker_run_options:
    - --privileged
    input_data:
      azure_storage:
      - storage_account_settings: mystorageaccount
        remote_path: seismic
        local_path: $AZ_BATCH_TASK_WORKING_DIR/seismic
    # multi_instance:
    #   num_instances: pool_current_dedicated
    #   mpi:
    #     runtime: mpich
    #     processes_per_node: 1
    command: python3 seismic/scripts/application.py
