job_specifications:
- id: gtpoc9
  auto_complete: true
  tasks:
  - docker_image:  slimcontainers.azurecr.io/azure_devito_mpich:v0.8
    additional_docker_run_options:
    - --privileged
    # multi_instance:
    #   num_instances: pool_current_dedicated
    #   mpi:
    #     runtime: mpich
    #     processes_per_node: 1
    command: python3 /app/test_script_no_mpi.py
