batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
    - slimdockerwest.azurecr.io/devito_time_reversal:v0.2
  volumes:
    shared_data_volumes:
      azureblob_vol:
        volume_driver: azureblob
        storage_account_settings: mystorageaccount
        azure_blob_container_name: overthrust
        container_path: $AZ_BATCH_NODE_SHARED_DIR/overthrust
        bind_options: rw
        mount_options:
          - --file-cache-timeout-in-seconds=0
